### PR TITLE
Update lib/schedule_attributes/input.rb

### PR DESCRIPTION
**Pull request by markedmondson**
You can't strftime a string, which params[:start_time] would be.

### CODE REVIEW

**Comment by markedmondson** [comment]
Currently fails, try in console:

<pre><code>@params = {:start_time => "10:00"}
ScheduleAttributes::Input.new(@params).dates</pre></code>

=> NoMethodError: undefined method `strftime' for "10:00":String
from /home/vagrant/.rvm/gems/ruby-1.9.3-p286/bundler/gems/schedule_attributes-b423cb4250cb/lib/schedule_attributes/input.rb:134:in`dates'

**Comment by markedmondson** [comment]
Actually it doesn't even look like the variable time is used in this function at all?

**Comment by avit** [comment]
Yeah, looks right. Reading the start time _is_ needed to get correct dates in current zone.

Can you add a spec for inputs.rb to confirm the fix?

**Comment by avit** [comment]
Merged with the specs you added, thanks.

**Pull request closed without merging**
