### PR TITLE
Upgrade IceCube to 0.11.2

### PR DESCRIPTION
**Pull request by dgilperez**

### CODE REVIEW

**Comment by avit** [comment]
Hi, thanks for the PR, it's nice to see that someone is using this, but I have a couple of questions about it:
1. I'm not sure what's happening with the "weird syntax error" you're seeing: I'm not seeing any error there.
2. The version dependency on IceCube in the gemspec is just a _minimum_ version number. This shouldn't stop you from using a newer version if you just `bundle update ice_cube` in your app.

**Comment by dgilperez** [comment]
Hey!

Yeah, we're using schedule_attributes in production, not with a few glitches so to say. Anyway, it does the job for us ;)
1. This was like one year ago, I don't remember how to reproduce the error. It may be related to a particular Ruby version, if I recall correctly. It hurt at the time and it was our motivation for the fork. As long as it is a minor change, I hope you don't mind if we keep it our version, so we don't find the bug back again by surprise.
2. Reverted.

I rebased everything in one single commit.

**Comment by dgilperez** [comment]
Hmm I didn't want to add the last commit to this pull request, but another one to solve #18 ...

**Comment by avit** [comment]
Sure, I'll take a look and merge it or else just cherry-pick what we need.

**Comment by dgilperez** [comment]
Hey @avit, just pinging here to let you know my fork seems to work properly under Rails 4.1, with the last couple of commits. I also upgraded `ice_cube` to 0.12. I did not test it throughly yet, but it's looking good for the moment.

**Comment by avit** [comment]
Cheers, I'll have a look. Currently only using this on a rails-3.2 project myself, but we definitely should update it to work for all the current versions.

**Comment by dgilperez** [comment]
Hey @avit, any chance that this get merged anytime soon? Thanks and regards!

**Pull request closed without merging**
